### ISSUE TITLE
Challenge Mode Bug

### ISSUE THREAD

**Issue by IchorDragon** [MisaLiu/phi-chart-render#1]
So basically I'm trying Challenge Mode and somehow if I try to Restart after finishing a round, it'll looks like this 
![Screenshot_20221021_100956](https://user-images.githubusercontent.com/116325809/197096129-2b1c1ca1-6574-463c-a0d1-bfe4f1693cfd.jpg)
And if I restart again it'll be 
![Screenshot_20221021_101230](https://user-images.githubusercontent.com/116325809/197096158-d28ad29b-65d0-4732-b23c-d5f833685c0c.jpg)
It'll be infinitely stacking

**Comment by MisaLiu** [comment]
Fixed
