### ISSUE TITLE
iOS加載不出來 全報錯

### ISSUE THREAD

**Issue by LangerFox** [MisaLiu/phi-chart-render#10]
![921BD6FC-A9DD-417E-9096-F2082DFD7720](https://user-images.githubusercontent.com/68113694/217452724-f7935238-4fa0-4b68-b67d-d2740f1a4450.png)

**Comment by LangerFox** [comment]
看網頁上面那句怨念很深 想問是目前解決不了嗎？

**Comment by MisaLiu** [comment]
不过目前你提供的这张报错截图可以先定位到音乐资源加载器有问题，这几天会尝试更换一下加载器写法

**Comment by LangerFox** [comment]
好

**Comment by MisaLiu** [comment]
Hi  尝试修改了下  还麻烦测试看看

**Comment by LangerFox** [comment]
![BCC076BA-F94A-4DB4-BDAA-20689C78F5E7](https://user-images.githubusercontent.com/68113694/219937075-a9bef351-8be6-47a1-b657-4a605ff9a641.png)
還是我的連結是舊的？ 能傳一下嗎

**Comment by MisaLiu** [comment]
应该不会哇？看一下 git hash 是不是 5880c38 打头？

**Comment by MisaLiu** [comment]
翻了一下 howler.js 的 issue 列表，貌似还是因为 safari 不支持解码 ogg 导致的问题（goldfire/howler.js#1330）

稍候尝试添加一个 ogg 解码库看看能不能解决这个问题

**Comment by LangerFox** [comment]
Git hash是對的

**Comment by LangerFox** [comment]
好的

**Comment by MisaLiu** [comment]
哈啰～刚刚更新了一下，还请帮忙测试看看

**Comment by LangerFox** [comment]
可以了～ 只是我幀數有點低 可能我板子舊 或 瀏覽器不對 反正可以正常運行了 
好耶
