### ISSUE TITLE
Audio error 

### ISSUE THREAD

**Issue by Nekitori17** [MisaLiu/phi-chart-render#15]
Intermittent error 
![Screenshot_2023-05-02-14-01-37-852_com android chrome](https://user-images.githubusercontent.com/129297098/235601080-027159c6-7dee-41bb-887f-a68a8faa9e75.jpg)

**Comment by Nekitori17** [comment]
Sorry for the late reply
Device info:
 +Redmi Note 7
 +Snapdragon 660
 +Ram 4GB
 +Rom 64GB
 +Miui 12.5 Global (Android 10)
File chart: https://pan.baidu.com/s/1TvXs_ceU09OC3k7_sUKM8g?dp-logid=13315100795920150002&pwd=time#/home/%2F/%2F

**Comment by MisaLiu** [comment]
> Sorry for the late reply Device info: +Redmi Note 7 +Snapdragon 660 +Ram 4GB +Rom 64GB +Miui 12.5 Global (Android 10) File chart: https://pan.baidu.com/s/1TvXs_ceU09OC3k7_sUKM8g?dp-logid=13315100795920150002&pwd=time#/home/%2F/%2F

Works fine on my laptop, can you descripe what you've done when error occurred?

**Comment by Nekitori17** [comment]
When I loaded a chart file and adjusted other settings in the Visual and Sound sections, then pressed Start, the chart began faster than the music and when I restarted it, it added countless other play windows, causing the sound to loop repeatedly

**Comment by MisaLiu** [comment]
> When I loaded a chart file and adjusted other settings in the Visual and Sound sections, then pressed Start, the chart began faster than the music and when I restarted it, it added countless other play windows, causing the sound to loop repeatedly

Sounds weird, any screenrecord?

**Comment by Nekitori17** [comment]
I Misremembered, It doesn't add any additional play windows but only repeats the sound continuously.

**Comment by Nekitori17** [comment]
I Misremembered, It doesn't add any additional play windows but only repeats the sound continuously.
Video: https://imgur.com/a/48XoYJl

**Comment by MisaLiu** [comment]
> I Misremembered, It doesn't add any additional play windows but only repeats the sound continuously. Video: https://imgur.com/a/48XoYJl

What's the browser you are using?

There's an audio problem with Xiaomi Browser iirc, so can you try play the same chart with Google Chrome / [Kiwi Browser](https://github.com/kiwibrowser/src.next) ?

**Comment by Nekitori17** [comment]
I am using the latest version of Chrome browser and I am also using the app installation feature."

**Comment by MisaLiu** [comment]
Hi, tried revoke 84f8e4e ,please try again

**Comment by Nekitori17** [comment]
> Hi, tried revoke [84f8e4e](https://github.com/MisaLiu/phi-chart-render/commit/84f8e4ec4bd470e5e0e6b90943cdf7265d74f967) ,please try again

"I haven't played long enough to identify all the mistakes, but the issue of skipping a section at the beginning of the chart causes the chart to be out of sync with the music."

**Comment by MisaLiu** [comment]
I'll close this issue as complete, you can re-open this issue if error still occurs or create a new issue for other questions.
