### ISSUE TITLE
[bug report]播放时点击右上角暂停之后，再次点击不会关闭弹窗

### ISSUE THREAD

**Issue by irasutoya** [MisaLiu/phi-chart-render#16]
![image](https://github.com/MisaLiu/phi-chart-render/assets/98635300/ee7d921a-2d96-4189-b042-7d84c33da4eb)
如图，再次点击右上角播放，弹窗不会消失，这可能是一个bug

**Comment by MisaLiu** [comment]
不是影响体验的大问题，目前不考虑这个
