### ISSUE TITLE
文本事件不支持%P%

### ISSUE THREAD

**Issue by IchorDragon** [MisaLiu/phi-chart-render#17]
一般上如果文本事件是0%P%至100%P%应该是0慢慢变成100（好像1,2,3,...,100）但是出现了整个0%P%的字而不是0，也没有渐变的效果

**Comment by MisaLiu** [comment]
是的，这个还没有做

**Comment by MisaLiu** [comment]
已修复，烦请测试。

如果仍有问题请重新打开这个 issue。
