### ISSUE TITLE
第二次播放谱面时一些自定义判定线会大小异常

### ISSUE THREAD

**Issue by chenxy914** [MisaLiu/phi-chart-render#4]
![Screenshot_20221119_183159_com kiwibrowser browser](https://user-images.githubusercontent.com/116572560/202846444-369e1aa7-5f81-4722-a813-e70d94413e46.jpg)
上图是建立在我服务器上的phi-chart-render，再第二次播放谱面之后，一些自定义判定线便出现大小异常

**Comment by MisaLiu** [comment]
稍微有点好奇为啥要自己部署

**Comment by chenxy914** [comment]
我不道啊，可能因为web转应用网址扒不出来，不过这确实是是一个bug（）

**Comment by MisaLiu** [comment]
> 我不道啊，可能因为web转应用网址扒不出来，不过这确实是是一个bug（）

我前几天不是做了 pwa，理论上浏览器支持就可以当作一个 app 安装哇？）

**Comment by chenxy914** [comment]
a那行吧（）

**Comment by MisaLiu** [comment]
兄啊这 bug 都没修你关什么啊

**Comment by chenxy914** [comment]
~~不好意思我是懂Github的~~

**Comment by MisaLiu** [comment]
Fixed [224f77e](https://github.com/MisaLiu/phi-chart-render/commit/224f77e9111abed02ad1ce6fe07498d99145a6fd)
