### ISSUE TITLE
关于为什么帧数很高但看起来却很卡的问题

### ISSUE THREAD

**Issue by xLin7648** [MisaLiu/phi-chart-render#7]
game.js
//performance.now() / 1e3
let currentTime = (this.chart.music.seek() || 0) - this.chart.offset + this._settings.offset;

但需要另行适配暂停等功能

**Comment by MisaLiu** [comment]
[抛弃音频引擎自带的音频计时器，使用自制音频计时器](https://github.com/MisaLiu/phi-chart-render/commit/2323cdedc7a87bf9dd931bbe430f570d44624d17)
