### ISSUE TITLE
On the copyright of texture assets

### ISSUE THREAD

**Issue by Mivik** [MisaLiu/phi-chart-render#8]
Are the texture assets in this repo licensed under GPLv3 as well? I'm working on my Phigros simulator project (which is licensed under GPLv3) and is intended to use these assets in my project.

**Comment by MisaLiu** [comment]
follow [CC-BY-NC-4.0](https://creativecommons.org/licenses/by-nc/4.0/).

you can repoen this issue if u have any other issues about the copyright of these assets.
