### ISSUE TITLE
iPadOS上无法正确显示

### ISSUE THREAD

**Issue by jamyido** [MisaLiu/phi-chart-render#9]
ipad上使用safari（夸克也试了）打开点击start后浏览器并未做出正确显示，safari直接跑到后面，夸克等无反应
iOS version：16.2

**Comment by MisaLiu** [comment]
https://misaliu.github.io/phi-chart-render/?debug=true 尝试使用这个链接，并打开左下角的 vConsole 看看是什么错误

**Comment by MisaLiu** [comment]
vConsole 没有任何报错？

**Comment by MisaLiu** [comment]
「无任何反应」是指？

**Comment by MisaLiu** [comment]
> 

右下角的 vConsole 也没有弹出？vConsole 里没有任何内容（包括 debug 模式警告）？

**Comment by MisaLiu** [comment]
那太奇怪了......判断是脚本本体卡加载了

**Comment by MisaLiu** [comment]
好几天前就有在 iOS 卡加载脚本的反馈...但是我没有 iOS 设备也就一直没法马上尝试调试。

这下来看貌似不是什么好修的问题

**Comment by MisaLiu** [comment]
> > 能看看调用栈吗？
> 
> 请问在哪里看啊不太会调

点一下单个报错

**Comment by MisaLiu** [comment]
那我推测是 ServiceWorker 出问题了，麻烦您本地部署一下 [6ea265e](https://github.com/MisaLiu/phi-chart-render/commit/6ea265e28cc70cea539fe4f24d1a22fdc089c34e) 看看是否能在浏览器里正常运行

**Comment by MisaLiu** [comment]
> 那我推测是 ServiceWorker 出问题了，麻烦您本地部署一下 [6ea265e](https://github.com/MisaLiu/phi-chart-render/commit/6ea265e28cc70cea539fe4f24d1a22fdc089c34e) 看看是否能在浏览器里正常运行

啊啊应该是这个 commit 的上一个 commit（[4b70742](https://github.com/MisaLiu/phi-chart-render/commit/4b70742dbaa04a9d83be82637bb390529703f839)）才对

**Comment by MisaLiu** [comment]
> > 这个版本可以正常使用，但是点击声音反馈似乎没了
> 
> [4b70742](https://github.com/MisaLiu/phi-chart-render/commit/4b70742dbaa04a9d83be82637bb390529703f839)

这个 commit 的下一个 commit 也能使用吗？

**Comment by MisaLiu** [comment]
那 (444c1a8)[https://github.com/MisaLiu/phi-chart-render/commit/444c1a89975eae53e8485a09afeb75200154e186] 可以正常使用嘛

**Comment by MisaLiu** [comment]
那试一下 e2109bd ，可能是资源加载器的问题

**Comment by MisaLiu** [comment]
好的清楚了，晚上回去尝试一下修复

**Comment by MisaLiu** [comment]
以及这个错误能看一眼控制台是什么错误嘛

**Comment by MisaLiu** [comment]
> > 以及这个错误能看一眼控制台是什么错误嘛
> 
> commit的几个版本中没有发现控制台按钮

这一 commit 还没有加 vConsole，你可以参考 [官方仓库](https://github.com/Tencent/vConsole) 手动添加到 `/public/index.html`

**Comment by MisaLiu** [comment]
确认了，就是资源加载器的问题

这几天会尝试修复

**Comment by MisaLiu** [comment]
01cd277 尝试在 ios 上不注册 ServiceWorker 了，还麻烦您测试一下

如果不行可尝试访问 https://misaliu.github.io/phi-chart-render/?unregistServiceWorker=true
